### PR TITLE
allow clearing of element's content

### PR DESCRIPTION
**Pull request by shakhraj**

### CODE REVIEW

**Comment by bjuppa** [comment]
Hi @shakhraj, first of all, big thanks for the first PR to this fluent-html package! So nice to see someone using it, and taking the time to dive deeper too, like you have!

Just to keep everyone up to date here, I originally wrote this package working for FEW, but I'm no longer employed by them, I run my own business nowadays. However, I guess I'm still the package maintainer, so I'll gladly take a look at the PR :)

I'll have to get myself reacquainted with the structure and history of this package, then I'll get back to you!

**Comment by bjuppa** [comment]
I've been thinking about this PR (the code itself looks good by the way)...

As it does expose a new method in the API (making `withoutContent()` public), I'd like to discuss an example use cases where having access to this method would improve the users code in some way, or make a new use case possible.

I think I was intentionally not exposing that method in the API when I originally wrote it, but I don't remember exactly :)

@shakhraj did you have any example situation in mind when you wrote this PR?

**Comment by shakhraj** [comment]
Thank you for taking the time to go back to this package and reviewing my pull request!

I was creating a link widget by extending FluentHtmlElement and I wanted it to have some default text and to be able to replace it in some cases:
```php
  class MyLink extends \FewAgency\FluentHtml\FluentHtmlElement {

    public function __construct()
    {
      parent::__construct();
      $this->withHtmlElementName('a');
      $this->withAttribute('href', 'http://example.com/');
      $this->withContent('some standart link text');
    }

  }

  print (new MyLink())
    ->withoutContent()
    ->withContent('custom link text');
```

But after your comment I'm not sure that it's a good way: I should probably just pass link content to constructor and use default content if nothing passed.

**Comment by bjuppa** [comment]
Thanks for the example @shakhraj , I see what you're trying to achieve!

I think I'd do exactly like your example but replace the call to `withContent()` in the constructor to  use `withDefaultContent()` instead. Then after newing up an instance you have the choice to call `withContent()` if you want something special, or just leave it if you want the default. Then there's no need to clear the existing contents of an instance!

There's just a short line about it in the readme here: https://github.com/fewagency/fluent-html#withdefaultcontenthtml_contents

So either that or passing an argument through the constructor as you suggested, but I think using `withDefaultContent()` could be a little less cluttered!

**Comment by shakhraj** [comment]
Don't know how I missed this method (
Sorry for taking your time and thanks for your help!
I'll remove this pull request

**Comment by bjuppa** [comment]
Absolutely no problem at all @shakhraj, I'm thankful for your interest and investment in this package!

**Pull request closed without merging**
